global:
  scrape_interval: 1s # Scrape every 1 second for real-time dashboards!

scrape_configs:
  - job_name: "raft_cluster"
    static_configs:
      - targets: ["replica1:5000", "replica2:5001", "replica3:5002", "replica4:5003"]
